### PR TITLE
Cannot update ssl certificate when update listener

### PR DESCRIPTION
**Pull request by Niklaus-xie**
Update listener success, but only the name and description of the
listener has been updated. Certificate remains same as old one.

Change-Id: I35aa3ca8d77f5cd58d8bd945fadc1061ecf05112
Closes-Bug: #1753656
(cherry picked from commit d87d0e3bd275d88e9beb5c4e9c2e1750893268d4)

### CODE REVIEW

**Comment by zhaoqin-github** [comment]
Cherry-pick in community

https://review.openstack.org/#/c/598091/
https://review.openstack.org/#/c/598100/
https://review.openstack.org/#/c/598129/
https://review.openstack.org/#/c/550298/

**Comment by zhaoqin-github** [comment]
@Niklaus-xie I fetched ocata cherry pick commit. Please review #20. Will cherry pick it to newton and mitaka after #20 is merged. Thanks!

**Comment by Niklaus-xie** [comment]
actually got so many cherry picks in the msg(all not merged in the community),  if any of those id changes in the community(which means will finally not be found in community O, P, etc), you would end up with some rubbish ids in the commit msg(which can not be found in community).  

I would suggest either do it one by one(until one merged), or cherry pick directly from master instead, which won't risk in any potential rubbish ids(or potential maintenance work ).

Anyway,   each way looks fine to me .

**Comment by zhaoqin-github** [comment]
Ocata patch has been merged by community. https://review.openstack.org/#/c/550298/

Will cherry-pick it to M/N branch. Close this PR.

**Pull request closed without merging**
